### ISSUE TITLE
Slide... (and porta mento) 

### ISSUE THREAD

**Issue by KJinx101** [Birch-san/juicysfplugin#16]
This plug-in has been serving me very well! It's been working better than the legacy soundfont player that it's basically replacing in FL! I opened up an old 8-bit project and realized that I utilized that a lot using FL's native features. Slide and portamento namely. I can't explain that well so, here is a video that basically shows the functionality, though you may already be familiar
https://www.youtube.com/watch?v=E9Z6T5qdFP0

Since FL handles the slide and porta mento itself, outside plugins need to have their own ways and I think I might have an idea of what could work

For this, I really like how a plug in called 'Mini Erhu' handles it
![image](https://user-images.githubusercontent.com/52682204/75306019-6cb76980-580d-11ea-8a40-a2864fdc26bd.png)
That poly button to the left switches the mono/poly mode of course, but while in mono mode, notes that are triggered while another note is playing pitch-shift the sample. the portamento is basically controlled by that glide knob (which can be automated). It basically pitch-shifts the sample that is currently being played to the next triggered notes pitch at a given speed (that the knob is turned to).

Since portamento is a standard speed, I guess that would be like having the knob at a very low value, and the slide is almost like having an automated knob...  so I guess both are covered. 

If you come back to this, I hope this would not be too troublesome to consider! Thanks a lot for your work!

**Comment by bahburah** [comment]
I second this.

This plugin is almost perfect. The sound quality is amazing and it has ADSR.

If only there was a pitch shift option to automate at the very least

**Comment by KJinx101** [comment]
There actually is a pitch-shift (bend) already that works with your DAW's native pitch wheel mapping (Like if you have a midi keyboard) and it can be automated. 

Automating a glide like that would be pretty tedious though

**Comment by Birch-san** [comment]
@KJinx101 What you show in the YouTube video looks pretty cool, but I think the underlying synthesizer (fluidsynth) doesn't expose any easy way to do that.

Your suggestion of automating a glide knob to change the speed of portamento... maybe we can do that already? I pass every MIDI CC event on to FluidSynth. They do support portamento.

http://www.nortonmusic.com/midi_cc.html

I think you could try sending a CC 65 to enable portamento (assuming it's not on by default), and then automate MIDI CC 5 Portamento Time -- that sounds like it's for changing portamento speed (same as the "glide" knob).

@bahburah pitch shift [is supported](https://github.com/Birch-san/juicysfplugin/blob/master/Source/FluidSynthModel.cpp#L362); we accept the standard MIDI Pitch Bend Event. but yeah, it'd be hard to implement glide with that.

**Comment by KJinx101** [comment]
Ah, I see! Didn't realize fluid already may support that. I think I'll be able to test this out using patcher and the midi out using FL. Thanks

**Comment by KJinx101** [comment]
It works like a charm! Seems like on/off can be turned on at 100% including mono. I just used something (fl color mapper) to map the channels for poly, mono, "porta," and "slide" [to automate] and then used a few instances of another plug in called midi polysher to send the CC's with the buttons in patcher. Now I basically have all of the same functionality.

**Comment by Birch-san** [comment]
Amazing! glad it turned out to be possible. :)
