### ISSUE TITLE
The whole thing doesn't work on FL-Studio 12 32-Bits.

### ISSUE THREAD

**Issue by ZackoDum** [Birch-san/juicysfplugin#24]
![Screenshot_3](https://user-images.githubusercontent.com/76856532/115783174-e952c300-a392-11eb-82e6-a3dab4fe54e3.png)
It installs, it loads up just fine on FL-Studio 12 (32Bits) but when i load any soundfont it doesn't show the patches

**Comment by Birch-san** [comment]
hm… are you using the 64-bit juicysfplugin with the 32-bit FL Studio?

which release of juicysfplugin did you download & install? please download & install [juicysfplugin-2.3.3-x86.zip](https://github.com/Birch-san/juicysfplugin/releases/download/2.3.3/juicysfplugin-2.3.3-x86.zip).

Once installed, compare the files on your computer with the files listed in the "32-bit" section of the [release notes](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.3). Does your computer have the files described there?

Have you tried both VST and VST3?

The problem in your screenshot looks like `libfluidsynth-2.dll` or `libglib-2.0-0.dll` (or any of the DLLs that they depend on) are not in the expected place.

You can also attempt a manual installation by reading [these instructions](https://github.com/Birch-san/juicysfplugin/issues/20#issuecomment-723877163), but referring to the [release notes](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.3) to determine which files are needed for 32-bit.

**Comment by ZackoDum** [comment]
![image](https://user-images.githubusercontent.com/76856532/115786562-5e27fc00-a397-11eb-824e-419bf6703823.png)
Everything seems to check ok

**Comment by ZackoDum** [comment]
![image](https://user-images.githubusercontent.com/76856532/115786668-80217e80-a397-11eb-9a24-3213bb6182ab.png)
Sorry for the cluttering, i tried running the standalone exe and nothing too

**Comment by Birch-san** [comment]
what version of Windows is this?

does your system have two Program Files folder (i.e. `"C:\Program Files"` and `"C:\Program Files (x86)"`)?

are all of the DLLs from the [release notes](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.3) listed inside your `"C:\Windows\SysWOW64"` directory?

**Comment by ZackoDum** [comment]
> what version of Windows is this?
> 
> does your system have two Program Files folder (i.e. `"C:\Program Files"` and `"C:\Program Files (x86)"`)?
> 
> are all of the DLLs from the [release notes](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.3) listed inside your `"C:\Windows\SysWOW64"` directory?

Its windows 7 32-bits

**Comment by ZackoDum** [comment]
> what version of Windows is this?
> 
> does your system have two Program Files folder (i.e. `"C:\Program Files"` and `"C:\Program Files (x86)"`)?
> 
> are all of the DLLs from the [release notes](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.3) listed inside your `"C:\Windows\SysWOW64"` directory?

and no, windows 32bits obviously doesn't have Syswow64 since it is basicly System32 but for 64bit windows

**Comment by Birch-san** [comment]
then, are all of the 32-bit DLLs from the release notes listed inside your `"C:\Windows\System32"` directory?

**Comment by ZackoDum** [comment]
> then, are all of the 32-bit DLLs from the release notes listed inside your `"C:\Windows\System32"` directory?

Yupp, i just placed them there and this happended
![image](https://user-images.githubusercontent.com/76856532/115788518-135bb380-a39a-11eb-953b-5afe436362c9.png)

**Comment by ZackoDum** [comment]
> > then, are all of the 32-bit DLLs from the release notes listed inside your `"C:\Windows\System32"` directory?
> 
> ![image](https://user-images.githubusercontent.com/76856532/115788518-135bb380-a39a-11eb-953b-5afe436362c9.png)
> Yupp, i just placed them there and this happended the dll is present there, but


![image](https://user-images.githubusercontent.com/76856532/115789269-405c9600-a39b-11eb-9e01-dafa97566c30.png)
The Manual Installation doesn't work, the automated installation works perfectly, but the SF patches doesn't show up

**Comment by Birch-san** [comment]
Use [Fusion Log Viewer](https://techcommunity.microsoft.com/t5/iis-support-blog/fusion-log-viewer-fuslogvw-exe/ba-p/784396) to log the error that occurs during assembly binding when juicysfplugin.exe is launched.
