### ISSUE TITLE
VST3/AU, Ableton: "Cannot be opened because the developer cannot be verified"

### ISSUE THREAD

**Issue by kristianpedersen** [Birch-san/juicysfplugin#27]
Ableton Live 11.0.12
MacOS 12.0.1
JuicySF 2.3.3

<img width="252" alt="Screenshot 2021-11-29 at 20 40 04" src="https://user-images.githubusercontent.com/5204369/143931894-bd2ba75b-1b5c-4095-aafd-300ca2b3d45c.png">

Happens with both VST and AU.

If this were an application, I'd just open it in Finder, right-click, and open.

It did show up here (.vst3), but allowing it to run didn't have any effect.

<img width="663" alt="Screenshot 2021-11-29 at 23 16 18" src="https://user-images.githubusercontent.com/5204369/143951425-095bd0d3-ebb3-44a7-b059-cd3d066dabd2.png">

I also tried following these instructions: https://www.reddit.com/r/ableton/comments/galkk3/macos_catalina_10154_and_vsts_vst_cannot_be/, but `spctl` wasn't available, and then I gave up and kept making music for a couple of hours. 😃

**Comment by Birch-san** [comment]
did you try the other suggestion:

```bash
xattr -rd com.apple.quarantine juicysfplugin.vst3
```

**Comment by kristianpedersen** [comment]
That worked!

For anyone else struggling, this is what I did:

1. Open iTerm
2. Paste this: `cd ~/Library/Audio/Plug-Ins/VST3`
3. Enter `open .` to open Finder, and copy `juicysfplugin.vst3` from your download directory
4. Paste this: `xattr -rd com.apple.quarantine juicysfplugin.vst3`

If step 2 fails, you might need to create a `VST3` folder there first:

1. `cd ~/Library/Audio/Plug-Ins`
2. `mkdir VST3`
3. `cd VST3`
4. Then you can follow steps 3 and 4 above.
