### ISSUE TITLE
Suggestion: Make the instrument change and ADSR directly react from MIDI messages

### ISSUE THREAD

**Issue by brickblock369** [Birch-san/juicysfplugin#36]
Basically, I think it would be useful if the plugin was able to be used like another MIDI synth from multiple MIDI channels, with the capabilities I mentioned in the subject.

**Comment by Birch-san** [comment]
Do you want something different than the MIDI event handling that's already implemented?

> Supports the following MIDI events:  
> - 192 program change (this changes soundfont preset)
> - CC 73 Attack time
> - CC 75 Decay Time
> - CC 79 undefined (being used as Sustain time)
> - CC 72 Release time

**Comment by brickblock369** [comment]
Nevermind. I'm testing the CCs out as you mentioned, and I don't think there's anything that I can think of to suggest.
