### ISSUE TITLE
Cubase 12 HATES this plugin

### ISSUE THREAD

**Issue by ApolloWAVE** [Birch-san/juicysfplugin#37]
Hello I hope all is well. I'm using cubase 12 and while using the plugin it works just great. BUT loading a session with it crashes cubase like crazy. i love soundfonts and need help or a fix.

**Comment by Birch-san** [comment]
is this on macOS or Windows? which version are you using?

what kind of crash? does it hang? does the whole DAW hang, or just juicysfplugin? or does it crash, rather than hang?

is the juicysfplugin GUI visible when this happens? what does it look like?

**Comment by ApolloWAVE** [comment]
Sorry for the late reply. To answer your questions....

1) Windows 10

2) The crash is that Cubase either wont load the program and carshes once it starts loading the plugin or I have to try loading it quite a few times and THEN it will load the project OR ill have to do a work around by loading the project in a special way.

3) the plugin is visable once the project loads but the problem is that cubase hates where the installed program is located so it would carsh cubase.

i reinstalled the plug in and the recommended spot rather then my vst HD and it seems to be working properly now.

now i just have recommendations to make the plugin better lol

If I have any issues in the future ill make sure to go back to this, and say what's going on but i have seemed to fixed this issue.

All the best.

**Comment by Birch-san** [comment]
phew 😅 thanks for confirming that changing the install location made a difference. not sure what the explanation is though.

**Comment by ApolloWAVE** [comment]
cubase hates a lot of plugins and stuff but it seems that everything is still good. love your plugin. any future developments on it?
