### ISSUE TITLE
Any plans for ASDR support?

### ISSUE THREAD

**Issue by lrcaldwell** [Birch-san/juicysfplugin#4]
I would like to know if there are any plans for ASDR support (Attack, Sustain, Decay, Release) in the future. This is pretty much a perfect replacement for FL Studio’s own Soundfont Player (which is not available on the Mac edition) but does not quite have feature parity. Regardless, I have been searching for something like this for a while. This seems to be the only plugin that can handle Soundfonts with multiple instruments correctly!

**Comment by Birch-san** [comment]
I must confess, I'd never used that feature.

<img src="https://user-images.githubusercontent.com/6141784/59802429-f5762100-92e0-11e9-9b8e-07349cb3ead5.png" width="300">

[Fruity SoundFont Player Manual](https://www.image-line.com/support/flstudio_online_manual/html/plugins/Fruity%20Soundfont%20Player.htm)

> **Envelope2 Section**
> You can use this section to override the volume envelope settings used in the SoundFont instrument. The four sliders represent the Attack (A), Decay (D), Sustain /s, Release (R) levels of the SoundFont envelope. Keep these sliders set to minimum to disable overriding of the predefined values. 

I've looked a bit at the fluidsynth codebase and don't immediately understand how to build this.

I assume it involves adding a default modulator (similar to https://github.com/Birch-san/juicysfplugin/issues/2#issuecomment-397872150). I never successfully got that to make any audible difference to the sound; there wasn't much documentation.

Probably these ([`src/synth/fluid_gen.c`](https://github.com/FluidSynth/fluidsynth/blob/master/src/synth/fluid_gen.c#L63-L68) [`include/fluidsynth/gen.h`](https://github.com/FluidSynth/fluidsynth/blob/f52e4fdf39b7444baa8d93b6794148fd7193bd30/include/fluidsynth/gen.h#L63-L68)) are the generator params that are involved.

Your proposal sounds like it could be some kind of globally-configured envelope, whereas Archer's proposal https://github.com/Birch-san/juicysfplugin/issues/2#issuecomment-397803893 involved controlling envelopes via MIDI commands. Which sounds harder, but perhaps could solve both problems with the same solution. I also wonder whether there's some idiomatic way to enable [General MIDI Level 2](https://en.wikipedia.org/wiki/General_MIDI#General_MIDI_Level_2) features in fluidsynth.

**Comment by Birch-san** [comment]
@lrcaldwell I've exposed these programmatically.

https://github.com/Birch-san/juicysfplugin/releases/tag/2.1.0

juicysfplugin now forwards MIDI CC messages to fluidsynth, and I've configured fluidsynth to map the following [GM2 CC messages](https://en.wikipedia.org/wiki/General_MIDI#General_MIDI_Level_2) such that they modulate envelopes.

- MIDI CC 71 = Timbre/Harmonic Intensity (filter resonance)
- MIDI CC 72 = Release time
- MIDI CC 73 = Attack time
- MIDI CC 74 = Brightness (cutoff frequency, FILTERFC)
- MIDI CC 75 = Decay Time

**Comment by Birch-san** [comment]
![image](https://user-images.githubusercontent.com/6141784/60401921-32af9e00-9b80-11e9-8e3a-6c5717f868d6.png)
[Release 2.2.0](https://github.com/Birch-san/juicysfplugin/releases/tag/2.2.0) provides a GUI for manipulating envelopes.

MIDI CC messages also work (in case you want to automate).

**Comment by KJinx101** [comment]
I really wanted to say AMAZING work on this plugin! This saves so many people who rely heavily on soundfonts and use workstations that are dropping support for sf2's and sf3's.  This is the may be the best soundfont player I've ever used, and with ASDR and Cut/Res, I think'll it'll top good ol Fruity Soundfont Player as well. 

Also, one thing I wanted to add was (after the stable release of ASDR, Cut/Res, and Pitch Bend) perhaps the addition of some sort of Mod Wheel Envelope. In Plogue's SFZ plugin, they use CC001 to create a sort of 'vibrato'ey filter.  I hadn't thought of this at all, but when I heard your demo used chip-tune styled soundfonts, I thought about how electronic instruments would largely benefit from this CC# especially as an automation  tool or with performance when using the mod wheel. 

Once again, thanks for your work on this amazing plugin

**Comment by Birch-san** [comment]
thanks for the kind words. I'm actively working to stabilise this release — mostly the mundane bits like how to save the last-selected value, and restore it when the synth is re-opened. all the hard questions are answered, so just working my way through all the parameters and rewriting older stuff to use the new patterns.

hey, looks like we actually CC001 support already. there's no GUI for it, but I think that's acceptable for parameters that are used for note-control rather than instrument control (the parameters are presumably saved as MIDI messages in your performance).

as of release 2.1.0, we forward all MIDI CC messages into fluidsynth. fluidsynth automatically provides the ten "default modulators" prescribed in the [SoundFont Specification v2.4](http://freepats.zenvoid.org/sf2/sfspec24.pdf).

> 8.4.4  MIDI Continuous Controller 1 to Vibrato LFO Pitch Depth

that looks like the modulator you're referring to.

**Comment by Birch-san** [comment]
ADSR is now fully-supported as of [release 2.3.0](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.0).

**Comment by donarturo11** [comment]
@Birch-san Because you added codes to original fluidsynth, I would like ask you, how to assign CC to modulator. I found control modulators only by NRPNs. Do you have any idea to patch original fluidsynth?
