### ISSUE TITLE
Legato / Portmento function?

### ISSUE THREAD

**Issue by Inversil** [Birch-san/juicysfplugin#40]
Hey!

I love what you're doing with JuicySFplugin.
How difficult would it be to add midi legato for easier pitch transitions on things like violins / guitars?
Would really improve the usability of soundfonts in general.

Thanks so much

**Comment by Birch-san** [comment]
Thanks! Probably it already supports legato and portamento. I pass every MIDI CC down to the underlying synthesized, FluidSynth:
https://github.com/Birch-san/juicysfplugin/blob/c95eb5755aab634a22dfa778912facd136590d5c/Source/FluidSynthModel.cpp#L361

And FluidSynth has had support for legato & portamento for years:
https://github.com/FluidSynth/fluidsynth/issues/158

So, try sending the appropriate MIDI CCs and see what happens!

**Comment by Birch-san** [comment]
This was mentioned previously; apparently it's possible:
https://github.com/Birch-san/juicysfplugin/issues/16

**Comment by Inversil** [comment]
Ohh! Ok! I figured it would be missing since I couldn't find any buttons for it. 

I send the right midi ccs into it it will enable the feature? amazing! I will try it out right now.

EDIT: sorry for creating a duplicate issue

**Comment by Inversil** [comment]
hmm well, It seems to be able to make the instrument monophonic; new midi notes kill previous ones (CC68). I can't seem to get the pitch bending to work using (CCs 65, 5, 37)
