### ISSUE TITLE
2.3.0 Release crashes FL Studio Mac 

### ISSUE THREAD

**Issue by lrcaldwell** [Birch-san/juicysfplugin#8]
Hi birch, just wanted to say that I **greatly** appreciate your work on this plugin- It is a god send for working with sound fonts on the Mac. However, 2.3.0 is crashing FL Studio for me. I have tried the Audio Unit, the VST and the VST3. The AU and VST will detect and allow selection in FL Plugin Manager / Plugin Picker but will crash the program at the step "Loading Fruity Wrapper". The VST3 will not allow for selection, FL Plugin Manager returns "error" and will not attempt to load the plugin. 

The plugin seems to be working fine in Ableton 10.1 though. 

juicysf 2.3.0
FL Studio 20.5.1 build 522
macOS Mojave 10.14.6

**Comment by Birch-san** [comment]
thanks for telling me. I'd been doing all my testing in JUCE's audio plugin host, so I missed this. FL Studio is the most important DAW, so definitely need to get this working.

the issue reproduces for me also; I've tried adding an instance of the AU plugin to an FL Studio project. A white rectangle is rendered, mouse cursor beachballs.

I've attached a debugger to OsxFL, and I've hit "pause" on program execution to see where it's hung:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/6141784/62323880-2df04980-b4a0-11e9-924d-1d5adc2ef08b.png">

It gets to the first line of initialising FluidSynthModel, and hangs whilst trying to allocate a `new_fluid_settings()`. specifically it's waiting to acquire some kind of mutex. `fluid_audio_settings` is nearby, so I wonder whether this is the same deadlock that we had on the previous version of FluidSynth (FL Studio wants exclusive access to CoreAudio, so fluidsynth waits forever).

**Comment by Birch-san** [comment]
if indeed this is the same deadlock, then this is how I fixed it last time:

```c++
// deactivate all audio drivers in fluidsynth to avoid FL Studio deadlock when initialising CoreAudio
// after all: we only use fluidsynth to render blocks of audio. it doesn't output to audio driver.
const char *DRV[] {NULL};
fluid_audio_driver_register(DRV);
```

I've just now tried shuffling that line up by one so that it occurs before we attempt to create `new_fluid_settings()`, but that didn't help. maybe a different workaround is needed in FluidSynth2.

pretty much all configurability of fluidsynth requires that you first succeed in creating a settings object. we're a bit constrained because we can't even get as far as that.

**Comment by Birch-san** [comment]
okay yeah; it's the same deadlock as we had in fluidsynth1:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6141784/62325940-d0123080-b4a4-11e9-864f-d2daca9c31bc.png">

inside `new_fluid_settings()` fluidsynth invokes `fluid_core_audio_driver_settings()` to set up a default audio driver (which we don't want anyway). it tries to ask how many outputs the driver has, but FL Studio has a lock on the audio object, so we have to wait (forever) to get our answer.

I wonder why the usual trick (asking to disable all audio drivers) has stopped working.

**Comment by Birch-san** [comment]
oh, actually: my fix did work (moving the audio driver deregistration code). the only problem was that I wasn't doing a sufficiently clean build.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/6141784/62326429-f6849b80-b4a5-11e9-8836-e5a8f827fde6.png">

**Comment by Birch-san** [comment]
@lrcaldwell please tell me whether release [2.3.1](https://github.com/Birch-san/juicysfplugin/releases/tag/2.3.1) is working any better for you.

**Comment by lrcaldwell** [comment]
@Birch-san 2.3.1 is now working in FL, still works in Ableton too. Thank you!~
